version: "3.8"

services:
    search-service:
        build:
            context: ../..
            dockerfile: Search-service/Dockerfile
        container_name: search-service
        restart: on-failure
        environment:
            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/Library-realm
            SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
            SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
            SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
            DISABLE_SECURITY_PLUGIN: true
        ports:
            - "8086:8080"
        networks:
            - Library-net


networks:
  Library-net:
    external: true